// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// extract_model_metadata_cpp
List extract_model_metadata_cpp(std::string encoded_content);
RcppExport SEXP _evaluatr_extract_model_metadata_cpp(SEXP encoded_contentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type encoded_content(encoded_contentSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_model_metadata_cpp(encoded_content));
    return rcpp_result_gen;
END_RCPP
}
// predict_from_encoded_cpp
List predict_from_encoded_cpp(std::string encoded_content, std::string model_type, NumericMatrix design_matrix, NumericVector outcome_vec, SEXP by_vec, SEXP model_params);
RcppExport SEXP _evaluatr_predict_from_encoded_cpp(SEXP encoded_contentSEXP, SEXP model_typeSEXP, SEXP design_matrixSEXP, SEXP outcome_vecSEXP, SEXP by_vecSEXP, SEXP model_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type encoded_content(encoded_contentSEXP);
    Rcpp::traits::input_parameter< std::string >::type model_type(model_typeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type design_matrix(design_matrixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type outcome_vec(outcome_vecSEXP);
    Rcpp::traits::input_parameter< SEXP >::type by_vec(by_vecSEXP);
    Rcpp::traits::input_parameter< SEXP >::type model_params(model_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_from_encoded_cpp(encoded_content, model_type, design_matrix, outcome_vec, by_vec, model_params));
    return rcpp_result_gen;
END_RCPP
}
// obfuscate_coefficients_cpp
NumericVector obfuscate_coefficients_cpp(NumericVector real_values, std::string obfuscation_key);
RcppExport SEXP _evaluatr_obfuscate_coefficients_cpp(SEXP real_valuesSEXP, SEXP obfuscation_keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type real_values(real_valuesSEXP);
    Rcpp::traits::input_parameter< std::string >::type obfuscation_key(obfuscation_keySEXP);
    rcpp_result_gen = Rcpp::wrap(obfuscate_coefficients_cpp(real_values, obfuscation_key));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_evaluatr_extract_model_metadata_cpp", (DL_FUNC) &_evaluatr_extract_model_metadata_cpp, 1},
    {"_evaluatr_predict_from_encoded_cpp", (DL_FUNC) &_evaluatr_predict_from_encoded_cpp, 6},
    {"_evaluatr_obfuscate_coefficients_cpp", (DL_FUNC) &_evaluatr_obfuscate_coefficients_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_evaluatr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
