# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Extract model metadata from base64-encoded JSON content
#'
#' @description
#' Decodes the base64 GitHub API content string and returns only metadata
#' (model type, variable names, preprocessing code). Does NOT return
#' coefficient values.
#'
#' @param encoded_content Character. Base64-encoded JSON string from GitHub
#'   Contents API.
#' @return A named R list containing model_type, variable_names,
#'   model_name, version, preprocessing, is_multinomial,
#'   category_names, has_obfuscation_key, model_parameters_present.
#'
#' @keywords internal
.extract_model_metadata_cpp <- function(encoded_content) {
    .Call(`_evaluatr_extract_model_metadata_cpp`, encoded_content)
}

#' Full secure prediction pipeline
#'
#' @description
#' Decodes base64 content, de-obfuscates coefficients, computes predictions,
#' shuffles outcome-prediction pairs, wipes coefficient data, and returns only
#' the shuffled results. Coefficients never exist as readable R objects.
#'
#' @param encoded_content Character. Base64-encoded JSON from GitHub API.
#' @param model_type Character. Model type string from metadata.
#' @param design_matrix Numeric matrix. Rows = observations, columns = terms
#'   (intercept first if present, then predictors in order).
#' @param outcome_vec Numeric vector. Outcome variable values.
#' @param by_vec Character/numeric vector (or R NULL). Subgroup variable.
#' @param model_params Named list (or NULL) with additional model parameters
#'   passed from R for reference: timepoints, baseline_survival, etc.
#'   (Actually these are parsed from JSON; the R list is used only for
#'   future extensibility and is currently ignored -- parameters come from JSON.)
#' @return A named R list with shuffled_outcomes, shuffled_predictions (logistic)
#'   or prediction_matrix (multi-column), shuffled_by (if by_vec non-null).
#'
#' @keywords internal
.predict_from_encoded_cpp <- function(encoded_content, model_type, design_matrix, outcome_vec, by_vec, model_params) {
    .Call(`_evaluatr_predict_from_encoded_cpp`, encoded_content, model_type, design_matrix, outcome_vec, by_vec, model_params)
}

#' Obfuscate coefficient values
#'
#' @description
#' Takes real coefficient values and returns obfuscated values using the
#' affine transform: stored = (real * mult) + offset, where mult and offset
#' are deterministically generated from the obfuscation_key plus compiled salts.
#' Used by the developer utility (Phase 2) when creating model JSON files.
#'
#' @param real_values Named numeric vector of real coefficient values.
#' @param obfuscation_key Character. 32-character hex string.
#' @return Named numeric vector of obfuscated values.
#'
#' @keywords internal
.obfuscate_coefficients_cpp <- function(real_values, obfuscation_key) {
    .Call(`_evaluatr_obfuscate_coefficients_cpp`, real_values, obfuscation_key)
}

